[tool.briefcase]
project_name = "Castor Analytics"
bundle = "com.rbeesoft"
version = "0.0.1"
url = "https://rbeesoft.nl/castoranalytics"
author = "Ralph Brecheisen"
author_email = "ralph.brecheisen@gmail.com"

[tool.briefcase.license]
file = "LICENSE"

[tool.briefcase.app.castoranalytics]
formal_name = "CastorAnalytics"
description = "Desktop application to view summary statistics and advanced visualizations of your Castor EDC studies"
long_description = "More details about the app should go here.\n"
sources = [
    "src/castoranalytics",
]
test_sources = [
    "tests",
]
requires = [
    "altgraph==0.17.4",
    "anyio==4.9.0",
    "arrow==1.3.0",
    "binaryornot==0.4.4",
    "briefcase==0.3.23",
    "build==1.2.2.post1",
    "certifi==2025.4.26",
    "chardet==5.2.0",
    "charset-normalizer==3.4.2",
    "click==8.2.1",
    "colorama==0.4.6",
    "cookiecutter==2.6.0",
    "gitdb==4.0.12",
    "GitPython==3.1.44",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "idna==3.10",
    "iniconfig==2.1.0",
    "Jinja2==3.1.6",
    "markdown-it-py==3.0.0",
    "MarkupSafe==3.0.2",
    "mdurl==0.1.2",
    "Nuitka==2.7.5",
    "ordered-set==4.1.0",
    "packaging==25.0",
    "pefile==2023.2.7",
    "platformdirs==4.3.8",
    "pluggy==1.6.0",
    "psutil==7.0.0",
    "Pygments==2.19.1",
    "pyinstaller==6.13.0",
    "pyinstaller-hooks-contrib==2025.4",
    "pyproject_hooks==1.2.0",
    "PySide6_Essentials==6.9.0",
    "pytest==8.4.0",
    "python-dateutil==2.9.0.post0",
    "python-slugify==8.0.4",
    "pywin32-ctypes==0.2.3",
    "PyYAML==6.0.2",
    "requests==2.32.3",
    "rich==14.0.0",
    "shiboken6==6.9.0",
    "six==1.17.0",
    "smmap==5.0.2",
    "sniffio==1.3.1",
    "text-unidecode==1.3",
    "tomli==2.2.1",
    "tomli_w==1.2.0",
    "types-python-dateutil==2.9.0.20250516",
    "typing_extensions==4.14.0",
    "urllib3==2.4.0",
    "zstandard==0.23.0",
]
test_requires = [
    "pytest",
]

[tool.briefcase.app.castoranalytics.macOS]
universal_build = true
min_os_version = "12.0"
requires = [
    "std-nslog~=1.0.3",
]

[tool.briefcase.app.castoranalytics.linux]
requires = []

[tool.briefcase.app.castoranalytics.linux.system.debian]
system_requires = []
system_runtime_requires = [
    "libxext6",
    "libxrender1",
    "libx11-xcb1",
    "libxkbcommon-x11-0",
    "libxcb-image0",
    "libxcb-cursor0",
    "libxcb-shape0",
    "libxcb-randr0",
    "libxcb-xfixes0",
    "libxcb-sync1",
    "libxcb-icccm4",
    "libxcb-keysyms1",
    "libfontconfig1",
    "libsm6",
    "libice6",
    "libglib2.0-0",
    "libgl1",
    "libegl1",
    "libdbus-1-3",
]

[tool.briefcase.app.castoranalytics.linux.system.rhel]
system_requires = []
system_runtime_requires = [
    "qt6-qtbase-gui",
]

[tool.briefcase.app.castoranalytics.linux.system.suse]
system_requires = []
system_runtime_requires = [
    "libgthread-2_0-0",
    "libQt6Gui6",
]

[tool.briefcase.app.castoranalytics.linux.system.arch]
system_requires = []
system_runtime_requires = [
    "qt6-base",
]

[tool.briefcase.app.castoranalytics.linux.appimage]
manylinux = "manylinux_2_28"
system_requires = []
linuxdeploy_plugins = []

[tool.briefcase.app.castoranalytics.linux.flatpak]
flatpak_runtime = "org.kde.Platform"
flatpak_runtime_version = "6.9"
flatpak_sdk = "org.kde.Sdk"

[tool.briefcase.app.castoranalytics.windows]
requires = []

[tool.briefcase.app.castoranalytics.iOS]
supported = false

[tool.briefcase.app.castoranalytics.android]
supported = false

[tool.briefcase.app.castoranalytics.web]
supported = false
