[tool.briefcase]
project_name = "Castor Analytics"
bundle = "com.rbeesoft"
icon = "src/castoranalytics/resources/images/icons/castoranalytics"
version = "1.1"
url = "https://rbeesoft.nl/castoranalytics"
author = "Ralph Brecheisen"
author_email = "ralph.brecheisen@gmail.com"

[tool.briefcase.license]
file = "LICENSE"

[tool.briefcase.app.castoranalytics]
formal_name = "CastorAnalytics"
description = "Desktop application to view summary statistics and advanced visualizations of your Castor EDC studies"
long_description = "More details about the app should go here.\n"
sources = [
    "src/castoranalytics",
]
test_sources = [
    "tests",
]
requires = [
    "pyside6==6.9.1",
    "sqlalchemy==2.0.41",
    "oauthlib==3.2.2",
    "requests-oauthlib==2.0.0",
]
test_requires = [
    "pytest",
]
resources = [
    "src/castoranalytics/resources",
]

[tool.briefcase.app.castoranalytics.macOS]
universal_build = true
min_os_version = "12.0"
requires = [
    "std-nslog~=1.0.3",
]

[tool.briefcase.app.castoranalytics.linux]
requires = []

[tool.briefcase.app.castoranalytics.linux.system.debian]
system_requires = []
system_runtime_requires = [
    "libxext6",
    "libxrender1",
    "libx11-xcb1",
    "libxkbcommon-x11-0",
    "libxcb-image0",
    "libxcb-cursor0",
    "libxcb-shape0",
    "libxcb-randr0",
    "libxcb-xfixes0",
    "libxcb-sync1",
    "libxcb-icccm4",
    "libxcb-keysyms1",
    "libfontconfig1",
    "libsm6",
    "libice6",
    "libglib2.0-0",
    "libgl1",
    "libegl1",
    "libdbus-1-3",
]

[tool.briefcase.app.castoranalytics.linux.system.rhel]
system_requires = []
system_runtime_requires = [
    "qt6-qtbase-gui",
]

[tool.briefcase.app.castoranalytics.linux.system.suse]
system_requires = []
system_runtime_requires = [
    "libgthread-2_0-0",
    "libQt6Gui6",
]

[tool.briefcase.app.castoranalytics.linux.system.arch]
system_requires = []
system_runtime_requires = [
    "qt6-base",
]

[tool.briefcase.app.castoranalytics.linux.appimage]
manylinux = "manylinux_2_28"
system_requires = []
linuxdeploy_plugins = []

[tool.briefcase.app.castoranalytics.linux.flatpak]
flatpak_runtime = "org.kde.Platform"
flatpak_runtime_version = "6.9"
flatpak_sdk = "org.kde.Sdk"

[tool.briefcase.app.castoranalytics.windows]
requires = []

[tool.briefcase.app.castoranalytics.iOS]
supported = false

[tool.briefcase.app.castoranalytics.android]
supported = false

[tool.briefcase.app.castoranalytics.web]
supported = false
